# Site settings
title: Map Frederick City
email:
url: https://www.mapfrederick City
description: "Data provided by the City of Frederick's IT department. This site was created and maintained by the Frederick Meetup Groups"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
#disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/frederickded
  - title: facebook
    url: https://www.facebook.com/CityofFrederick/
  - title: github
    url: https://github.com/AWSFrederick

# Postal address (add as many lines as necessary)
address:
  - line: Frederick, Maryland 21702

# Credits content
credits: 'Frederick Meetup Groups'

# Build settings
markdown: kramdown
permalink: pretty
