version: 0.1

phases:
  install:
    commands:
      - sed -i "s/YOUR_API_KEY/$APIKEY/g" index.html
  build:
    commands:
      - aws s3 sync ./ s3://map.awsfred.patrickpierson.us/
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id E3DMRHHC2OVUVW --paths "/*"
